--- 
title: "POLS0008: Introduction to Quantitative Research Methods"
author: Justin van Dijk^[Department of Geography, https://www.mappingdutchman.com/], Stephen Jivraj^[Institute of Epidemiology and Health Care, https://www.ucl.ac.uk/q-step/stephen-jivraj]
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: "jtvandijk/POLS0008_20202021"
description: "POLS0008: Introduction to Quantitative Research Methods."
url: 'https\://jtvandijk.github.io/POLS0008_20202021/'
---

# Welcome {-}

Welcome to **POLS0008: Introduction to Quantitative Research Methods**, one of the first year core module for students enrolled on Q-Step programmes and a second year methods option in BSc Philosophy, Politics and Economics. 

Before we start, please take a moment to read through the information below and watch the course introduction video. The video should answer any questions you may have with regard to the structure of the course, where to find your course materials, and what options you have when you have questions.

### Course Introduction {-}
```{r 00-short-lecture-welcome, warnings=FALSE, message=FALSE, echo=FALSE}
library(vembedr)
embed_msstream('b8ffcd14-34ef-4c85-8283-da1255b2165e') %>% use_align('left')
```
[[Lecture slides]](https://liveuclac-my.sharepoint.com/:b:/g/personal/ucfajtv_ucl_ac_uk/EdYf92pNXwBNgsoN_yVV05cBjO8-6_o57mAqsbZdRe7rtA?e=AhuQqM) [[Watch on MS stream]](https://web.microsoftstream.com/video/b8ffcd14-34ef-4c85-8283-da1255b2165e?list=studio)

### Moodle {-}
All important information and communication in relation to this module will be provided on [Moodle](https://moodle.ucl.ac.uk/course/view.php?id=6845). Even though for the first **4 weeks** all short lecture videos and practical materials will be hosted on this webpage, do check on Moodle **regularly** to see if there are any updates or important messages.

### Structure {-}
Although there may be some slight variation from week to week, the course is generally structured by several short lecture videos, reading material, a computer practical, a seminar task that you need to do in preparation of the live seminar, and a live seminar. Each week, all content for that week will be made available online by Monday morning. All live seminars take place on Thursday morning. This means that you have **3** days to go through all the materials and conduct your seminar task before it is discussed in the live seminar.

### Assessment {-}
This module is assessed by one 3,000 word essay (counting 100% towards your final mark for this course) based on secondary analysis of survey data. The assessment will be introduced by Dr Stephen Jivraj and more details will follow in later weeks.

### Technical support {-}
We do not offer any technical support. If you have any technical questions or encounter technical problems, you will have to take this up with the [IT Service Desk](https://www.ucl.ac.uk/isd/help-support). Similarly, for questions related to the organisation of the course (e.g. to which seminar group your get assigned to), you will have to direct your queries to the student office of your Department.

### Office hours {-}
Office hours with Dr Justin van Dijk (Tuesdays between 14h00 and 15h00) can be booked [here](https://outlook.office365.com/owa/calendar/JustinvanDijkBookableOfficeHours@ucl.ac.uk/bookings/). Office hours with Dr Stephen Jivraj (Tuesdays between 09h45 and 10h45) can be booked [here](https://outlook.office365.com/owa/calendar/StephenJivraj@ucl.ac.uk/bookings/). 
