<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Examining data I | POLS0008: Introduction to Quantitative Research Methods</title>
  <meta name="description" content="2 Examining data I | POLS0008: Introduction to Quantitative Research Methods." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Examining data I | POLS0008: Introduction to Quantitative Research Methods" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://jtvandijk.github.io/POLS0008_20202021/" />
  
  <meta property="og:description" content="2 Examining data I | POLS0008: Introduction to Quantitative Research Methods." />
  <meta name="github-repo" content="jtvandijk/POLS0008_20202021" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Examining data I | POLS0008: Introduction to Quantitative Research Methods" />
  
  <meta name="twitter:description" content="2 Examining data I | POLS0008: Introduction to Quantitative Research Methods." />
  

<meta name="author" content="Justin van Dijk, Stephen Jivraj" />


<meta name="date" content="2021-08-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="understanding-data.html"/>
<link rel="next" href="examining-data-ii.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<link href="libs/vembedr-0.1.4/css/vembedr.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/custom.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo">
<a href="https://www.ucl.ac.uk/module-catalogue/modules/introduction-to-quantitative-research-methods-POLS0008"><img src="images/general/ucl_logo.png">
</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-introduction"><i class="fa fa-check"></i>Course Introduction</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#moodle"><i class="fa fa-check"></i>Moodle</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure"><i class="fa fa-check"></i>Structure</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i>Assessment</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#technical-support"><i class="fa fa-check"></i>Technical support</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#office-hours"><i class="fa fa-check"></i>Office hours</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="understanding-data.html"><a href="understanding-data.html"><i class="fa fa-check"></i><b>1</b> Understanding data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="understanding-data.html"><a href="understanding-data.html#introduction-w01"><i class="fa fa-check"></i><b>1.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="understanding-data.html"><a href="understanding-data.html#reading-list-w01"><i class="fa fa-check"></i><b>1.1.1</b> Reading list</a></li>
<li class="chapter" data-level="1.1.2" data-path="understanding-data.html"><a href="understanding-data.html#qa-session"><i class="fa fa-check"></i><b>1.1.2</b> Q&amp;A session</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="understanding-data.html"><a href="understanding-data.html#data-and-statistics"><i class="fa fa-check"></i><b>1.2</b> Data and statistics</a></li>
<li class="chapter" data-level="1.3" data-path="understanding-data.html"><a href="understanding-data.html#r-for-data-analysis"><i class="fa fa-check"></i><b>1.3</b> R for data analysis</a></li>
<li class="chapter" data-level="1.4" data-path="understanding-data.html"><a href="understanding-data.html#r-console"><i class="fa fa-check"></i><b>1.4</b> R console</a></li>
<li class="chapter" data-level="1.5" data-path="understanding-data.html"><a href="understanding-data.html#r-script"><i class="fa fa-check"></i><b>1.5</b> R script</a></li>
<li class="chapter" data-level="1.6" data-path="understanding-data.html"><a href="understanding-data.html#seminar-w01"><i class="fa fa-check"></i><b>1.6</b> Seminar</a></li>
<li class="chapter" data-level="1.7" data-path="understanding-data.html"><a href="understanding-data.html#byl-w01"><i class="fa fa-check"></i><b>1.7</b> Before you leave</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="examining-data-i.html"><a href="examining-data-i.html"><i class="fa fa-check"></i><b>2</b> Examining data I</a>
<ul>
<li class="chapter" data-level="2.1" data-path="examining-data-i.html"><a href="examining-data-i.html#introduction-w02"><i class="fa fa-check"></i><b>2.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="examining-data-i.html"><a href="examining-data-i.html#reading-list-w02"><i class="fa fa-check"></i><b>2.1.1</b> Reading list</a></li>
<li class="chapter" data-level="2.1.2" data-path="understanding-data.html"><a href="understanding-data.html#qa-session"><i class="fa fa-check"></i><b>2.1.2</b> Q&amp;A session</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="examining-data-i.html"><a href="examining-data-i.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.2</b> Measures of central tendency</a></li>
<li class="chapter" data-level="2.3" data-path="examining-data-i.html"><a href="examining-data-i.html#simple-plots"><i class="fa fa-check"></i><b>2.3</b> Simple plots</a></li>
<li class="chapter" data-level="2.4" data-path="examining-data-i.html"><a href="examining-data-i.html#measures-of-dispersion"><i class="fa fa-check"></i><b>2.4</b> Measures of dispersion</a></li>
<li class="chapter" data-level="2.5" data-path="examining-data-i.html"><a href="examining-data-i.html#seminar-w02"><i class="fa fa-check"></i><b>2.5</b> Seminar</a></li>
<li class="chapter" data-level="2.6" data-path="examining-data-i.html"><a href="examining-data-i.html#byl-w02"><i class="fa fa-check"></i><b>2.6</b> Before you leave</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="examining-data-ii.html"><a href="examining-data-ii.html"><i class="fa fa-check"></i><b>3</b> Examining data II</a>
<ul>
<li class="chapter" data-level="3.1" data-path="examining-data-ii.html"><a href="examining-data-ii.html#introduction-w03"><i class="fa fa-check"></i><b>3.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="examining-data-ii.html"><a href="examining-data-ii.html#reading-list-w03"><i class="fa fa-check"></i><b>3.1.1</b> Reading list</a></li>
<li class="chapter" data-level="3.1.2" data-path="understanding-data.html"><a href="understanding-data.html#qa-session"><i class="fa fa-check"></i><b>3.1.2</b> Q&amp;A session</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="examining-data-ii.html"><a href="examining-data-ii.html#data-visualisation"><i class="fa fa-check"></i><b>3.2</b> Data visualisation</a></li>
<li class="chapter" data-level="3.3" data-path="examining-data-ii.html"><a href="examining-data-ii.html#ggplot2"><i class="fa fa-check"></i><b>3.3</b> ggplot2</a></li>
<li class="chapter" data-level="3.4" data-path="examining-data-ii.html"><a href="examining-data-ii.html#seminar-w03"><i class="fa fa-check"></i><b>3.4</b> Seminar</a></li>
<li class="chapter" data-level="3.5" data-path="examining-data-ii.html"><a href="examining-data-ii.html#byl-w03"><i class="fa fa-check"></i><b>3.5</b> Before you leave</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="sourcing-data.html"><a href="sourcing-data.html"><i class="fa fa-check"></i><b>4</b> Sourcing data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="sourcing-data.html"><a href="sourcing-data.html#introduction-w04"><i class="fa fa-check"></i><b>4.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="sourcing-data.html"><a href="sourcing-data.html#reading-list-w04"><i class="fa fa-check"></i><b>4.1.1</b> Reading list</a></li>
<li class="chapter" data-level="4.1.2" data-path="understanding-data.html"><a href="understanding-data.html#qa-session"><i class="fa fa-check"></i><b>4.1.2</b> Q&amp;A session</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="sourcing-data.html"><a href="sourcing-data.html#sourcing-data-1"><i class="fa fa-check"></i><b>4.2</b> Sourcing data</a></li>
<li class="chapter" data-level="4.3" data-path="sourcing-data.html"><a href="sourcing-data.html#preparing-data"><i class="fa fa-check"></i><b>4.3</b> Preparing data</a></li>
<li class="chapter" data-level="4.4" data-path="sourcing-data.html"><a href="sourcing-data.html#seminar-w04"><i class="fa fa-check"></i><b>4.4</b> Seminar</a></li>
<li class="chapter" data-level="4.5" data-path="sourcing-data.html"><a href="sourcing-data.html#byl-w04"><i class="fa fa-check"></i><b>4.5</b> Before you leave</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">POLS0008: Introduction to Quantitative Research Methods</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="examining-data-i" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Examining data I</h1>
<div id="introduction-w02" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Introduction</h2>
<p>Welcome to your second week of <strong>Introduction to Quantitative Research Methods</strong>. This week we will focus on <strong>examining data</strong> using measures of central tendency and measures of dispersion. These measures are collectively known as <strong>descriptive statistics</strong>. We will also talk about some basic data visualisation. Also, as by now everyone should be up and running with R, we will apply some of these descriptive measures onto some data. <a href="https://www.youtube.com/watch?v=LBduNcf1eQc">Nice</a>!</p>
<p>This week is structured by <strong>3</strong> short videos, practical material that you need to work through in preparation for Thursday’s seminar, and a seminar task that you need to do in preparation for Thursday’s seminar.</p>
<p>Let’s get to it.</p>
<div id="video-introduction-w02" class="section level4 unnumbered">
<h4>Video: Introduction W02</h4>
<p><div class="vembedr" align="left">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/40cef170-a483-44bf-b7ca-5b08ca4a790e?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
[Lecture slides] <a href="https://web.microsoftstream.com/video/40cef170-a483-44bf-b7ca-5b08ca4a790e">[Watch on MS stream]</a></p>
</div>
<div id="reading-list-w02" class="section level3" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Reading list</h3>
<p>Please find the reading list for this week below. We strongly recommend that you read the <strong>core reading material</strong> before you continue with the rest of this week’s material.</p>
<div id="core-reading" class="section level4 unnumbered">
<h4>Core reading</h4>
<ul>
<li>Lane <em>et al.</em>, 2003, <strong>Chapter 3: Summarizing Distributions</strong>. In: Lane <em>et al.</em>, 2003, Introduction to Statistics. Houston, Texas: Rice University. <a href="http://onlinestatbook.com/Online_Statistics_Education.pdf">[Link]</a></li>
</ul>
</div>
<div id="supplementary-reading" class="section level4 unnumbered">
<h4>Supplementary reading</h4>
<ul>
<li>Diez <em>et al.</em>, 2019, <strong>Chapter 2: Summarizing data</strong>. In: Diez <em>et al.</em>, 2019, OpenIntro Statistics. Fourth Edition. Boston, Massachusetts: OpenIntro.
<a href="https://leanpub.com/openintro-statistics">[Link]</a></li>
</ul>
</div>
</div>
<div id="qa-session" class="section level3" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Q&amp;A session</h3>
<p>This week there is <strong>NO</strong> live Q&amp;A session scheduled. Please post any questions you have on the <a href="https://moodle.ucl.ac.uk/mod/forum/view.php?id=1632137">POLS0008 Forum</a> or ask them to your seminar leader during your live seminar on Thursday.</p>
</div>
</div>
<div id="measures-of-central-tendency" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Measures of central tendency</h2>
<p>Any research project involving <a href="https://en.wikipedia.org/wiki/Quantitative_research">quantitative data</a> should start with an exploration and examination of the available data sets. This applies both to data that you have collected yourself and data that you have acquired in a different way, e.g. through downloading official <a href="https://www.nomisweb.co.uk/">UK Census and labour market statistics</a>. The set of techniques that is used to examine your data in first instance is called <a href="https://en.wikipedia.org/wiki/Descriptive_statistics">descriptive statistics</a>. Descriptive statistics are used to describe the basic features of your data set and provide simple summaries about your data. Together with simple visual analysis, they form the basis of virtually <strong>every</strong> quantitative data analysis.</p>
<div id="video-measures-of-central-tendency" class="section level4 unnumbered">
<h4>Video: Measures of central tendency</h4>
<p><div class="vembedr" align="left">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/a6169cec-43ad-4c3f-bda6-9cc8fc4575f5?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<a href="https://liveuclac-my.sharepoint.com/:b:/g/personal/ucfajtv_ucl_ac_uk/EdQtMgoDs4BPkvVXKqXPDjcBP1OllLAePoqYQM0JO0I8Yw?e=YvMuCS">[Lecture slides]</a> <a href="https://web.microsoftstream.com/video/a6169cec-43ad-4c3f-bda6-9cc8fc4575f5">[Watch on MS stream]</a></p>
<p>For this tutorial we will initially continue to use the <code>London.Pop</code> object that we created during last week’s tutorial. You may still have it loaded into your R workspace if your RStudio Server session is still active. To check if you do, you can use the <code>ls()</code> command to get a list of all objects that are available in your RStudio session. Type this into the command line and see if <code>London.Pop</code> is printed.</p>
<p>If not you can simply reload it:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="examining-data-i.html#cb61-1" aria-hidden="true"></a><span class="co"># set the working directory path to the folder you wish to use</span></span>
<span id="cb61-2"><a href="examining-data-i.html#cb61-2" aria-hidden="true"></a><span class="co"># this would be the folder that you created during last week&#39;s practical</span></span>
<span id="cb61-3"><a href="examining-data-i.html#cb61-3" aria-hidden="true"></a><span class="kw">setwd</span>(<span class="st">&#39;~/POLS0008&#39;</span>) </span>
<span id="cb61-4"><a href="examining-data-i.html#cb61-4" aria-hidden="true"></a><span class="co"># note the single / (\\ will also work)</span></span></code></pre></div>
<p>If you struggle with setting up your working directory and you need a reminder, <a href="understanding-data.html#working-directory">have a look at how we did this last week</a>!</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="examining-data-i.html#cb62-1" aria-hidden="true"></a><span class="co"># load csv file from working directory</span></span>
<span id="cb62-2"><a href="examining-data-i.html#cb62-2" aria-hidden="true"></a>London.Pop &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;census-historic-population-borough.csv&#39;</span>)</span></code></pre></div>
<p>Use the <code>head()</code>, or <code>View()</code>, function to remind yourself of the structure of the London population data frame. You should see <strong>25</strong> columns of data.</p>
</div>
<div id="questions" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>What is the difference between using <code>head()</code> and <code>View()</code> to inspect your data?</li>
<li>Can you combine the functions <code>View()</code> and <code>head()</code> to browse only through a few lines of your data?</li>
</ol>
<p>The <code>mean()</code> and <code>median()</code> were some of the first R functions we used last week to describe our <code>Friends</code> data frame Now we know a little more about these <strong>measures of central tendency</strong>, we can also apply them on our <code>London.Pop</code> data set. Let’s do this by focusing on London’s population in 2011.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="examining-data-i.html#cb63-1" aria-hidden="true"></a><span class="co"># select the relevant columns</span></span>
<span id="cb63-2"><a href="examining-data-i.html#cb63-2" aria-hidden="true"></a>London.Pop2011 &lt;-<span class="st"> </span>London.Pop[,<span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,<span class="dv">24</span>)]</span></code></pre></div>
</div>
<div id="questions-1" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>Do you remember what the <code>c()</code> function does? Why do we need to use the <code>c()</code> in this case?</li>
<li>Instead of using the <code>[ , ]</code> <a href="https://en.wikipedia.org/wiki/Syntax">syntax</a> to slice our data frame, how can we create the same <code>London.Pop2011</code> object by using the <code>$</code> syntax?</li>
</ol>
<p>Now we can calculate our <strong>measures of central tendency</strong> using R’s built-in functions for the median and the mean.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="examining-data-i.html#cb64-1" aria-hidden="true"></a><span class="co"># calculate the median of the 2011 population variable</span></span>
<span id="cb64-2"><a href="examining-data-i.html#cb64-2" aria-hidden="true"></a><span class="kw">median</span>(London.Pop2011<span class="op">$</span>Persons<span class="fl">.2011</span>)</span></code></pre></div>
<pre><code>## [1] 254096</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="examining-data-i.html#cb66-1" aria-hidden="true"></a><span class="co"># calculate the mean of the 2011 population variable</span></span>
<span id="cb66-2"><a href="examining-data-i.html#cb66-2" aria-hidden="true"></a><span class="kw">mean</span>(London.Pop2011<span class="op">$</span>Persons<span class="fl">.2011</span>)</span></code></pre></div>
<pre><code>## [1] 247695.2</code></pre>
</div>
<div id="questions-2" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>How do you explain that the median is larger than the mean for this variable?</li>
</ol>
<p>R does not have a standard in-built function to calculate the mode. As we still want to show the mode, we create a user function to calculate the mode of our data set. This function takes <a href="https://r4ds.had.co.nz/vectors.html">a numeric vector</a> as input and gives the mode value as output.</p>
<div class="note">
<p><strong>Note</strong><br/>
You do not have to worry about creating your own functions, so just copy and paste the code below to create the <code>get_mode()</code> function.</p>
</div>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="examining-data-i.html#cb68-1" aria-hidden="true"></a><span class="co"># create a function to calculate the mode</span></span>
<span id="cb68-2"><a href="examining-data-i.html#cb68-2" aria-hidden="true"></a>get_mode &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</span>
<span id="cb68-3"><a href="examining-data-i.html#cb68-3" aria-hidden="true"></a>  </span>
<span id="cb68-4"><a href="examining-data-i.html#cb68-4" aria-hidden="true"></a>  <span class="co"># get unique values of the input vector</span></span>
<span id="cb68-5"><a href="examining-data-i.html#cb68-5" aria-hidden="true"></a>  uniqv &lt;-<span class="st"> </span><span class="kw">unique</span>(x)</span>
<span id="cb68-6"><a href="examining-data-i.html#cb68-6" aria-hidden="true"></a>  </span>
<span id="cb68-7"><a href="examining-data-i.html#cb68-7" aria-hidden="true"></a>  <span class="co"># select the values with the highest number of occurrences</span></span>
<span id="cb68-8"><a href="examining-data-i.html#cb68-8" aria-hidden="true"></a>  uniqv[<span class="kw">which.max</span>(<span class="kw">tabulate</span>(<span class="kw">match</span>(x, uniqv)))]</span>
<span id="cb68-9"><a href="examining-data-i.html#cb68-9" aria-hidden="true"></a>}</span>
<span id="cb68-10"><a href="examining-data-i.html#cb68-10" aria-hidden="true"></a></span>
<span id="cb68-11"><a href="examining-data-i.html#cb68-11" aria-hidden="true"></a><span class="co"># calculate the mode of the 2011 population variable</span></span>
<span id="cb68-12"><a href="examining-data-i.html#cb68-12" aria-hidden="true"></a><span class="kw">get_mode</span>(London.Pop2011<span class="op">$</span>Persons<span class="fl">.2011</span>)</span></code></pre></div>
<pre><code>## [1] 7375</code></pre>
</div>
<div id="questions-3" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>What is the level of measurement of our <em>Persons.2011</em> variable? Nominal, ordinal, or interval/ratio?</li>
<li>Even though we went through all the trouble to create our own function to calculate the mode, do you think it is a good choice to calculate the mode for this variable? Why? Why not?</li>
</ol>
<p>Although R does most of the hard work for us, especially with the <code>mean()</code> and the <code>median()</code> function, it is a good idea to once go through the calculations of these two central tendency measures ourselves. Let’s cacluate the mean step-by-step and then verify our results with the results of R’s <code>mean()</code> function.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="examining-data-i.html#cb70-1" aria-hidden="true"></a><span class="co"># get the sum of all values</span></span>
<span id="cb70-2"><a href="examining-data-i.html#cb70-2" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Sum &lt;-<span class="st"> </span><span class="kw">sum</span>(London.Pop2011<span class="op">$</span>Persons<span class="fl">.2011</span>)</span>
<span id="cb70-3"><a href="examining-data-i.html#cb70-3" aria-hidden="true"></a></span>
<span id="cb70-4"><a href="examining-data-i.html#cb70-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb70-5"><a href="examining-data-i.html#cb70-5" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Sum</span></code></pre></div>
<pre><code>## [1] 8173941</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="examining-data-i.html#cb72-1" aria-hidden="true"></a><span class="co"># get the total number of observations</span></span>
<span id="cb72-2"><a href="examining-data-i.html#cb72-2" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Obs &lt;-<span class="st"> </span><span class="kw">length</span>(London.Pop2011<span class="op">$</span>Persons<span class="fl">.2011</span>)</span>
<span id="cb72-3"><a href="examining-data-i.html#cb72-3" aria-hidden="true"></a></span>
<span id="cb72-4"><a href="examining-data-i.html#cb72-4" aria-hidden="true"></a><span class="co"># inspect the result </span></span>
<span id="cb72-5"><a href="examining-data-i.html#cb72-5" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Obs</span></code></pre></div>
<pre><code>## [1] 33</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="examining-data-i.html#cb74-1" aria-hidden="true"></a><span class="co"># calculate the mean</span></span>
<span id="cb74-2"><a href="examining-data-i.html#cb74-2" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Mean &lt;-<span class="st"> </span>Persons.<span class="fl">2011.</span>Sum <span class="op">/</span><span class="st"> </span>Persons.<span class="fl">2011.</span>Obs</span>
<span id="cb74-3"><a href="examining-data-i.html#cb74-3" aria-hidden="true"></a></span>
<span id="cb74-4"><a href="examining-data-i.html#cb74-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb74-5"><a href="examining-data-i.html#cb74-5" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Mean</span></code></pre></div>
<pre><code>## [1] 247695.2</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="examining-data-i.html#cb76-1" aria-hidden="true"></a><span class="co"># compare our result with R&#39;s built-in function</span></span>
<span id="cb76-2"><a href="examining-data-i.html#cb76-2" aria-hidden="true"></a><span class="kw">mean</span>(London.Pop2011<span class="op">$</span>Persons<span class="fl">.2011</span>) <span class="op">==</span><span class="st"> </span>Persons.<span class="fl">2011.</span>Mean</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Great. Our own calculation of the mean is identical to R’s built-in function. Now let’s do the same for the median.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="examining-data-i.html#cb78-1" aria-hidden="true"></a><span class="co"># get the total number of observations</span></span>
<span id="cb78-2"><a href="examining-data-i.html#cb78-2" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Obs &lt;-<span class="st"> </span><span class="kw">length</span>(London.Pop2011<span class="op">$</span>Persons<span class="fl">.2011</span>)</span>
<span id="cb78-3"><a href="examining-data-i.html#cb78-3" aria-hidden="true"></a></span>
<span id="cb78-4"><a href="examining-data-i.html#cb78-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb78-5"><a href="examining-data-i.html#cb78-5" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Obs</span></code></pre></div>
<pre><code>## [1] 33</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="examining-data-i.html#cb80-1" aria-hidden="true"></a><span class="co"># order our data from lowest to highest</span></span>
<span id="cb80-2"><a href="examining-data-i.html#cb80-2" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Ordered &lt;-<span class="st"> </span><span class="kw">sort</span>(London.Pop2011<span class="op">$</span>Persons<span class="fl">.2011</span>, <span class="dt">decreasing=</span><span class="ot">FALSE</span>)</span>
<span id="cb80-3"><a href="examining-data-i.html#cb80-3" aria-hidden="true"></a></span>
<span id="cb80-4"><a href="examining-data-i.html#cb80-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb80-5"><a href="examining-data-i.html#cb80-5" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Ordered</span></code></pre></div>
<pre><code>##  [1]   7375 158649 160060 182493 185911 186990 190146 199693 206125 219396
## [11] 220338 231997 237232 239056 246270 253957 254096 254557 254926 258249
## [21] 273936 275885 278970 288283 303086 306995 307984 309392 311215 312466
##  [ reached getOption(&quot;max.print&quot;) -- omitted 3 entries ]</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="examining-data-i.html#cb82-1" aria-hidden="true"></a><span class="co"># get the number of the observation that contains the median value</span></span>
<span id="cb82-2"><a href="examining-data-i.html#cb82-2" aria-hidden="true"></a>Persons.Median.Obs &lt;-<span class="st"> </span>(Persons.<span class="fl">2011.</span>Obs <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)<span class="op">/</span><span class="dv">2</span></span>
<span id="cb82-3"><a href="examining-data-i.html#cb82-3" aria-hidden="true"></a></span>
<span id="cb82-4"><a href="examining-data-i.html#cb82-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb82-5"><a href="examining-data-i.html#cb82-5" aria-hidden="true"></a>Persons.Median.Obs</span></code></pre></div>
<pre><code>## [1] 17</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="examining-data-i.html#cb84-1" aria-hidden="true"></a><span class="co"># get the median</span></span>
<span id="cb84-2"><a href="examining-data-i.html#cb84-2" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Median &lt;-<span class="st"> </span>Persons.<span class="fl">2011.</span>Ordered[Persons.Median.Obs]</span>
<span id="cb84-3"><a href="examining-data-i.html#cb84-3" aria-hidden="true"></a></span>
<span id="cb84-4"><a href="examining-data-i.html#cb84-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb84-5"><a href="examining-data-i.html#cb84-5" aria-hidden="true"></a>Persons.<span class="fl">2011.</span>Median</span></code></pre></div>
<pre><code>## [1] 254096</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="examining-data-i.html#cb86-1" aria-hidden="true"></a><span class="co"># compare our result with R&#39;s built-in function</span></span>
<span id="cb86-2"><a href="examining-data-i.html#cb86-2" aria-hidden="true"></a><span class="kw">median</span>(London.Pop2011<span class="op">$</span>Persons<span class="fl">.2011</span>) <span class="op">==</span><span class="st"> </span>Persons.<span class="fl">2011.</span>Median</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="questions-4" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>For the calculation of the median: what does the <code>decreasing=FALSE</code> parameter in the <code>sort()</code> function do? What happens if we change this to <code>decreasing=TRUE</code>? Does this affect the results for the calculation of the median? Why? Why not?</li>
<li>When extracting the median we using <code>[Persons.Median.Obs]</code> and not <code>[17]</code> to select our value. Although the results are identical, what would be a good reason to select the first option over the second option?</li>
<li>When comparing our own calculation to R’s built-in function we are using two ‘equal to’ signs <code>==</code>, what happens if we only use one ‘equal to’ <code>=</code> sign? Why?</li>
</ol>
</div>
</div>
<div id="simple-plots" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Simple plots</h2>
<p>Before moving on to the second set of descriptive statistics, the <strong>measures of dispersion</strong>, this is a good moment to note that simple data visualisations are also an extremely powerful tool to explore your data. In fact, tools to create high quality plots have become one of R’s greatest assets. This is a relatively recent development since the software has traditionally been <a href="https://en.wikipedia.org/wiki/R_(programming_language)">focused on the statistics</a> rather than visualisation. The standard installation of R has base graphic functionality built in to produce very simple plots. For example we can plot the relationship between the London population in 1811 and 1911.</p>
<div class="note">
<p><strong>Note</strong><br/>
Next week we will be diving deeper into data visualisation and making plots and graphs in R, but for now it is a good idea to already take a sneak peek at how to create some basic plots.</p>
</div>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="examining-data-i.html#cb88-1" aria-hidden="true"></a><span class="co"># make a quick plot of two variables of the London population data set</span></span>
<span id="cb88-2"><a href="examining-data-i.html#cb88-2" aria-hidden="true"></a><span class="kw">plot</span>(London.Pop<span class="op">$</span>Persons<span class="fl">.1811</span>,London.Pop<span class="op">$</span>Persons<span class="fl">.1911</span>)</span></code></pre></div>
<p><img src="POLS0008_files/figure-html/02-quick-plot-1.png" width="672" /></p>
<div id="questions-5" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>What happens if you change the order of the variables you put in the <code>plot()</code> function? Why?</li>
<li>Instead of using the <code>$</code> to select the columns of our data set, how else can we get the same results?</li>
</ol>
<p>The result of calling the <code>plot()</code> function, is a very simple <a href="https://en.wikipedia.org/wiki/Scatter_plot">scatter graph</a>. The <code>plot()</code> function offers a huge number of options for customisation. You can see them using the <code>?plot</code> help pages and also the <code>?par</code> help pages (<code>par</code> in this case is short for parameters). There are some examples below (note how the parameters come after specifying the <code>x</code> and <code>y</code> columns).</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="examining-data-i.html#cb89-1" aria-hidden="true"></a><span class="co"># add a title, change point colour, change point size</span></span>
<span id="cb89-2"><a href="examining-data-i.html#cb89-2" aria-hidden="true"></a><span class="kw">plot</span>(London.Pop<span class="op">$</span>Persons<span class="fl">.1811</span>, London.Pop<span class="op">$</span>Persons<span class="fl">.1911</span>, <span class="dt">main=</span><span class="st">&#39;Quick Plot in R&#39;</span>, <span class="dt">col=</span><span class="st">&#39;blue&#39;</span>, <span class="dt">cex=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="POLS0008_files/figure-html/02-quick-plot-with-some-options-1.png" width="672" /></p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="examining-data-i.html#cb90-1" aria-hidden="true"></a><span class="co"># add a title, change point colour, change point symbol</span></span>
<span id="cb90-2"><a href="examining-data-i.html#cb90-2" aria-hidden="true"></a><span class="kw">plot</span>(London.Pop<span class="op">$</span>Persons<span class="fl">.1811</span>, London.Pop<span class="op">$</span>Persons<span class="fl">.1911</span>, <span class="dt">main=</span><span class="st">&quot;Another Quick Plot in R&quot;</span>, <span class="dt">col=</span><span class="st">&#39;magenta&#39;</span>, <span class="dt">pch=</span><span class="dv">22</span>)</span></code></pre></div>
<p><img src="POLS0008_files/figure-html/02-quick-plot-with-different-options-1.png" width="672" /></p>
<div class="note">
<p><strong>Note</strong><br/>
For more information on the plot parameters (some have obscure names) have a look here: <a href="http://www.statmethods.net/advgraphs/parameters.html" class="uri">http://www.statmethods.net/advgraphs/parameters.html</a></p>
</div>
</div>
<div id="recap" class="section level4 unnumbered">
<h4>Recap</h4>
<p>In this section you have learnt how to:</p>
<ol style="list-style-type: decimal">
<li>Calculate the mode, median, and mean of a variable in R.</li>
<li>Make some simple scatter plots (in preparation for next week) to visualise your data.</li>
</ol>
</div>
</div>
<div id="measures-of-dispersion" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Measures of dispersion</h2>
<p>When exploring your data, <strong>measures of central tendency</strong> alone are not enough as they only tell you what a ‘typical’ value looks like but they do not tell you anything about all other values. Therefore we also need to look at some <strong>measures of dispersion</strong>. Measures of dispersion describe the spread of data around a central value (e.g. the mean, the median, or the mode). The most commonly used measure of dispersion is the <a href="https://en.wikipedia.org/wiki/Standard_deviation">standard deviation</a>. The standard deviation is a measure to summarise the spread of your data around the mean. The short video below will introduce you to the standard deviation as well as to three other measures of dispersion: the <strong>range</strong>, the <strong>interquartile range</strong>, and the <strong>variance</strong>.</p>
<div id="video-measures-of-dispersion" class="section level4 unnumbered">
<h4>Video: Measures of dispersion</h4>
<p><div class="vembedr" align="left">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/8623cbd8-ab11-40f9-b987-f7e966db50db?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<a href="https://liveuclac-my.sharepoint.com/:b:/g/personal/ucfajtv_ucl_ac_uk/EQBtLckmEItBniy4Jh_toSEBJkOMZ5BKl5pid5BBvRNz0A?e=B01n4f">[Lecture slides]</a> <a href="https://web.microsoftstream.com/video/8623cbd8-ab11-40f9-b987-f7e966db50db">[Watch on MS stream]</a></p>
<p>For the rest of this tutorial we will change our data set to one containing the number of assault incidents that ambulances have been called to in London between 2009 and 2011. You will need to download a prepared version of this file called: <code>ambulance-assault.csv</code> and upload it to your working directory. It is in the same data format (<code>csv</code>) as our London population file so we use the <code>read.csv()</code> command again.</p>
</div>
<div id="file-download" class="section level4 unnumbered">
<h4>File download</h4>
<table>
<thead>
<tr class="header">
<th align="left">File</th>
<th align="left">Type</th>
<th align="left">Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Assault Incidents London</td>
<td align="left"><code>csv</code></td>
<td align="left"><a href="https://liveuclac-my.sharepoint.com/:f:/g/personal/ucfajtv_ucl_ac_uk/ElYO3yqJw8RPvhwt6zOu9psBGFyesL1-aTWjralbxIGkhQ?e=m3WVg9">Download</a></td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="examining-data-i.html#cb91-1" aria-hidden="true"></a><span class="co"># load csv file from working directory</span></span>
<span id="cb91-2"><a href="examining-data-i.html#cb91-2" aria-hidden="true"></a>London.Ambulance &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;ambulance-assault.csv&#39;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="examining-data-i.html#cb92-1" aria-hidden="true"></a><span class="co"># inspect the results </span></span>
<span id="cb92-2"><a href="examining-data-i.html#cb92-2" aria-hidden="true"></a><span class="kw">head</span>(London.Ambulance)</span></code></pre></div>
<pre><code>##   BorCode     WardName WardCode                WardType Assault_09_11
## 1    00AA   Aldersgate   00AAFA Prospering Metropolitan            10
## 2    00AA      Aldgate   00AAFB Prospering Metropolitan             0
## 3    00AA    Bassishaw   00AAFC Prospering Metropolitan             0
## 4    00AA Billingsgate   00AAFD Prospering Metropolitan             0
## 5    00AA  Bishopsgate   00AAFE Prospering Metropolitan           188
## 6    00AA Bread Street   00AAFF Prospering Metropolitan             0</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="examining-data-i.html#cb94-1" aria-hidden="true"></a><span class="co"># inspect the size of the data set</span></span>
<span id="cb94-2"><a href="examining-data-i.html#cb94-2" aria-hidden="true"></a><span class="kw">nrow</span>(London.Ambulance)</span></code></pre></div>
<pre><code>## [1] 649</code></pre>
<p>You will notice that the data table has 5 columns and 649 rows. The column headings are abbreviations of the following:</p>
<table>
<colgroup>
<col width="21%" />
<col width="21%" />
<col width="57%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Column heading</th>
<th align="left">Full name</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>BorCode</strong></td>
<td align="left">Borough Code</td>
<td align="left">London has 32 Boroughs (such as Camden, Islington, Westminster, etc.) plus the City of London at the centre. These codes are used as a quick way of referring to them from official data sources.</td>
</tr>
<tr class="even">
<td align="left"><strong>WardName</strong></td>
<td align="left">Ward Name</td>
<td align="left">Boroughs can be broken into much smaller areas known as <a href="https://en.wikipedia.org/wiki/Wards_and_electoral_divisions_of_the_United_Kingdom">Wards</a>. These are electoral districts and have existed in London for centuries.</td>
</tr>
<tr class="odd">
<td align="left"><strong>WardCode</strong></td>
<td align="left">Ward Code</td>
<td align="left">A statistical code for the wards above.</td>
</tr>
<tr class="even">
<td align="left"><strong>WardType</strong></td>
<td align="left">Ward Type</td>
<td align="left">A classification that groups wards based on similar characteristics.</td>
</tr>
<tr class="odd">
<td align="left"><strong>Assault_09_11</strong></td>
<td align="left">Assault Incidents</td>
<td align="left">The number of assault incidents requiring an ambulance between 2009 and 2011 for each ward in London.</td>
</tr>
</tbody>
</table>
<p>Let’s start by calculating two measures of central tendency by using the <code>median()</code> and <code>mean()</code> functions.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="examining-data-i.html#cb96-1" aria-hidden="true"></a><span class="co"># calculate the median of the assault incident variable</span></span>
<span id="cb96-2"><a href="examining-data-i.html#cb96-2" aria-hidden="true"></a><span class="kw">median</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span></code></pre></div>
<pre><code>## [1] 146</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="examining-data-i.html#cb98-1" aria-hidden="true"></a><span class="co"># calculate the mean of the assault incident variable</span></span>
<span id="cb98-2"><a href="examining-data-i.html#cb98-2" aria-hidden="true"></a><span class="kw">mean</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span></code></pre></div>
<pre><code>## [1] 173.4669</code></pre>
</div>
<div id="questions-6" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>How do you explain that the mean is larger than the median for this variable?</li>
</ol>
<p>Great. Let’s now calculate some measures of dispersion for our data: the range, the interquartile range, and the standard deviation. The calculation of the range is very straightforward as we only need to subtract the the minimum value from the the maximum value. We can find these values by using the built-in <code>min()</code> and <code>max()</code> functions.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="examining-data-i.html#cb100-1" aria-hidden="true"></a><span class="co"># get the minimum value of the assault incident variable</span></span>
<span id="cb100-2"><a href="examining-data-i.html#cb100-2" aria-hidden="true"></a><span class="kw">min</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="examining-data-i.html#cb102-1" aria-hidden="true"></a><span class="co"># get the maximum value of the assault incident variable</span></span>
<span id="cb102-2"><a href="examining-data-i.html#cb102-2" aria-hidden="true"></a><span class="kw">max</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span></code></pre></div>
<pre><code>## [1] 1582</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="examining-data-i.html#cb104-1" aria-hidden="true"></a><span class="co"># calculate the range</span></span>
<span id="cb104-2"><a href="examining-data-i.html#cb104-2" aria-hidden="true"></a><span class="dv">1582</span> <span class="op">-</span><span class="st"> </span><span class="dv">0</span></span></code></pre></div>
<pre><code>## [1] 1582</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="examining-data-i.html#cb106-1" aria-hidden="true"></a><span class="co"># or in one go</span></span>
<span id="cb106-2"><a href="examining-data-i.html#cb106-2" aria-hidden="true"></a><span class="kw">max</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span></code></pre></div>
<pre><code>## [1] 1582</code></pre>
</div>
<div id="questions-7" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>Why do we get a value of <code>0</code> when executing our <code>min()</code> function?</li>
<li>What does this range mean?</li>
</ol>
<p>The interquartile range requires a little bit more work to be done as we now need to work out the values of the 25th and 75th <a href="https://en.wikipedia.org/wiki/Percentile">percentile</a>.</p>
<div class="note">
<p><strong>Note</strong><br/>
A percentile is a score at or below which a given percentage of your data points fall. For example, the 50th percentile (also known as the median!) is the score at or below which 50% of the scores in the distribution may be found.</p>
</div>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="examining-data-i.html#cb108-1" aria-hidden="true"></a><span class="co"># get the total number of observations</span></span>
<span id="cb108-2"><a href="examining-data-i.html#cb108-2" aria-hidden="true"></a>London.Ambulance.Obs &lt;-<span class="st"> </span><span class="kw">length</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span>
<span id="cb108-3"><a href="examining-data-i.html#cb108-3" aria-hidden="true"></a></span>
<span id="cb108-4"><a href="examining-data-i.html#cb108-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb108-5"><a href="examining-data-i.html#cb108-5" aria-hidden="true"></a>London.Ambulance.Obs</span></code></pre></div>
<pre><code>## [1] 649</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="examining-data-i.html#cb110-1" aria-hidden="true"></a><span class="co"># order our data from lowest to highest</span></span>
<span id="cb110-2"><a href="examining-data-i.html#cb110-2" aria-hidden="true"></a>London.Ambulance.Ordered &lt;-<span class="st"> </span><span class="kw">sort</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>, <span class="dt">decreasing=</span><span class="ot">FALSE</span>)</span>
<span id="cb110-3"><a href="examining-data-i.html#cb110-3" aria-hidden="true"></a></span>
<span id="cb110-4"><a href="examining-data-i.html#cb110-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb110-5"><a href="examining-data-i.html#cb110-5" aria-hidden="true"></a>London.Ambulance.Ordered</span></code></pre></div>
<pre><code>##  [1]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10 18 19 21 22 25 28
## [24] 28 28 29 30 34 36 36
##  [ reached getOption(&quot;max.print&quot;) -- omitted 619 entries ]</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="examining-data-i.html#cb112-1" aria-hidden="true"></a><span class="co"># get the number (&#39;index value&#39;) of the observation that contains the 25th percentile</span></span>
<span id="cb112-2"><a href="examining-data-i.html#cb112-2" aria-hidden="true"></a>London.Ambulance.Q1 &lt;-<span class="st"> </span>(London.Ambulance.Obs <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)<span class="op">/</span><span class="dv">4</span></span>
<span id="cb112-3"><a href="examining-data-i.html#cb112-3" aria-hidden="true"></a></span>
<span id="cb112-4"><a href="examining-data-i.html#cb112-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb112-5"><a href="examining-data-i.html#cb112-5" aria-hidden="true"></a>London.Ambulance.Q1</span></code></pre></div>
<pre><code>## [1] 162.5</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="examining-data-i.html#cb114-1" aria-hidden="true"></a><span class="co"># get the number (&#39;index value&#39;) of the observation that contains the 75th percentile</span></span>
<span id="cb114-2"><a href="examining-data-i.html#cb114-2" aria-hidden="true"></a>London.Ambulance.Q3 &lt;-<span class="st"> </span><span class="dv">3</span><span class="op">*</span>(London.Ambulance.Obs <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)<span class="op">/</span><span class="dv">4</span></span>
<span id="cb114-3"><a href="examining-data-i.html#cb114-3" aria-hidden="true"></a></span>
<span id="cb114-4"><a href="examining-data-i.html#cb114-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb114-5"><a href="examining-data-i.html#cb114-5" aria-hidden="true"></a>London.Ambulance.Q3</span></code></pre></div>
<pre><code>## [1] 487.5</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="examining-data-i.html#cb116-1" aria-hidden="true"></a><span class="co"># get the 25th percentile</span></span>
<span id="cb116-2"><a href="examining-data-i.html#cb116-2" aria-hidden="true"></a>London.Ambulance.Ordered[<span class="dv">163</span>]</span></code></pre></div>
<pre><code>## [1] 86</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="examining-data-i.html#cb118-1" aria-hidden="true"></a><span class="co"># get the 75the percentile</span></span>
<span id="cb118-2"><a href="examining-data-i.html#cb118-2" aria-hidden="true"></a>London.Ambulance.Ordered[<span class="dv">488</span>]</span></code></pre></div>
<pre><code>## [1] 233</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="examining-data-i.html#cb120-1" aria-hidden="true"></a><span class="co"># get the interquartile range</span></span>
<span id="cb120-2"><a href="examining-data-i.html#cb120-2" aria-hidden="true"></a><span class="dv">233</span> <span class="op">-</span><span class="st"> </span><span class="dv">86</span></span></code></pre></div>
<pre><code>## [1] 147</code></pre>
<p>As explained in the short lecture video, we can also visually represent our range, median, and interquartile range using a box and whisker plot:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="examining-data-i.html#cb122-1" aria-hidden="true"></a><span class="co"># make a quick boxplot of our assault incident variable</span></span>
<span id="cb122-2"><a href="examining-data-i.html#cb122-2" aria-hidden="true"></a><span class="kw">boxplot</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>, <span class="dt">horizontal=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="POLS0008_files/figure-html/02-box-that-plot-1.png" width="672" /></p>
</div>
<div id="questions-8" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>There is a large difference between the range that we calculated and the interquartile range that we calculated. What does this mean?</li>
<li>The 25th and 75th percentile in the example do not return integer but a fraction (i.e. 162.5 and 487.5). Why do we use 163 and 488 to extract our percentile values and not 162 and 487?</li>
</ol>
<p>Now, let’s move to the standard deviation. Remember: this is one of the most important measures of dispersion and is widely used in all kinds of statistics. The calculation involves the following steps:</p>
<ol style="list-style-type: decimal">
<li>Calculate the mean.</li>
<li>Subtract the mean from each observation to get a residual.</li>
<li>Square each residual.</li>
<li>Sum all residuals.</li>
<li>Divide by <span class="math inline">\(n-1\)</span>.</li>
<li>Take the square root of the final number.</li>
</ol>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="examining-data-i.html#cb123-1" aria-hidden="true"></a><span class="co"># calculate the mean</span></span>
<span id="cb123-2"><a href="examining-data-i.html#cb123-2" aria-hidden="true"></a>London.Ambulance.Mean &lt;-<span class="st"> </span><span class="kw">mean</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span>
<span id="cb123-3"><a href="examining-data-i.html#cb123-3" aria-hidden="true"></a></span>
<span id="cb123-4"><a href="examining-data-i.html#cb123-4" aria-hidden="true"></a><span class="co"># subtract the mean from each observation</span></span>
<span id="cb123-5"><a href="examining-data-i.html#cb123-5" aria-hidden="true"></a>London.Ambulance.Res &lt;-<span class="st"> </span>London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span> <span class="op">-</span><span class="st"> </span>London.Ambulance.Mean</span>
<span id="cb123-6"><a href="examining-data-i.html#cb123-6" aria-hidden="true"></a></span>
<span id="cb123-7"><a href="examining-data-i.html#cb123-7" aria-hidden="true"></a><span class="co"># square each residual</span></span>
<span id="cb123-8"><a href="examining-data-i.html#cb123-8" aria-hidden="true"></a>London.Ambulance.Res.Sq &lt;-<span class="st"> </span>London.Ambulance.Res<span class="op">**</span><span class="dv">2</span></span>
<span id="cb123-9"><a href="examining-data-i.html#cb123-9" aria-hidden="true"></a></span>
<span id="cb123-10"><a href="examining-data-i.html#cb123-10" aria-hidden="true"></a><span class="co"># sum all squared residuals</span></span>
<span id="cb123-11"><a href="examining-data-i.html#cb123-11" aria-hidden="true"></a>London.Ambulance.Res.Sum &lt;-<span class="st"> </span><span class="kw">sum</span>(London.Ambulance.Res.Sq)</span>
<span id="cb123-12"><a href="examining-data-i.html#cb123-12" aria-hidden="true"></a></span>
<span id="cb123-13"><a href="examining-data-i.html#cb123-13" aria-hidden="true"></a><span class="co"># divide the sum of all sqaured residuals by n - 1</span></span>
<span id="cb123-14"><a href="examining-data-i.html#cb123-14" aria-hidden="true"></a>London.Ambulance.Variance &lt;-<span class="st"> </span>London.Ambulance.Res.Sum <span class="op">/</span><span class="st"> </span>(<span class="kw">length</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>) <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)</span>
<span id="cb123-15"><a href="examining-data-i.html#cb123-15" aria-hidden="true"></a></span>
<span id="cb123-16"><a href="examining-data-i.html#cb123-16" aria-hidden="true"></a><span class="co"># take the square root of the final number</span></span>
<span id="cb123-17"><a href="examining-data-i.html#cb123-17" aria-hidden="true"></a>London.Ambulance.Sd &lt;-<span class="st"> </span><span class="kw">sqrt</span>(London.Ambulance.Variance)</span>
<span id="cb123-18"><a href="examining-data-i.html#cb123-18" aria-hidden="true"></a></span>
<span id="cb123-19"><a href="examining-data-i.html#cb123-19" aria-hidden="true"></a><span class="co"># standard deviation</span></span>
<span id="cb123-20"><a href="examining-data-i.html#cb123-20" aria-hidden="true"></a>London.Ambulance.Sd</span></code></pre></div>
<pre><code>## [1] 130.3482</code></pre>
<p>There we go. We got our standard deviation! You probably already saw this coming, but R does have some built-in functions to actually calculate these descriptive statistics for us: <code>range()</code>, <code>IQR()</code>, and <code>sd()</code> will do all the hard work for us!</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="examining-data-i.html#cb125-1" aria-hidden="true"></a><span class="co"># range</span></span>
<span id="cb125-2"><a href="examining-data-i.html#cb125-2" aria-hidden="true"></a><span class="kw">range</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span></code></pre></div>
<pre><code>## [1]    0 1582</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="examining-data-i.html#cb127-1" aria-hidden="true"></a><span class="co"># interquartile range</span></span>
<span id="cb127-2"><a href="examining-data-i.html#cb127-2" aria-hidden="true"></a><span class="kw">IQR</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span></code></pre></div>
<pre><code>## [1] 147</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="examining-data-i.html#cb129-1" aria-hidden="true"></a><span class="co"># standard deviation</span></span>
<span id="cb129-2"><a href="examining-data-i.html#cb129-2" aria-hidden="true"></a><span class="kw">sd</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span></code></pre></div>
<pre><code>## [1] 130.3482</code></pre>
<div class="note">
<p><strong>Note</strong><br/>
Please be aware that the <code>IQR()</code> function may give slighlty different results in some cases when compared to a manual calculation. This is because the forumula that the <code>IQR()</code> function uses is slightly different than the formula that we have used in our manual calculation. It is noted in the documentation of the <code>IQR()</code> function that: “Note that this function computes the quartiles using the quantile function rather than following Tukey’s recommendations, i.e., <code>IQR(x) = quantile(x, 3/4) - quantile(x, 1/4)</code>.”</p>
</div>
</div>
<div id="questions-9" class="section level4 unnumbered">
<h4>Questions</h4>
<ol style="list-style-type: decimal">
<li>What does it mean that we have a standard deviation of 130.3482?</li>
<li>Given the context of the data, do you think this is a low or a high standard deviation?</li>
</ol>
<p>To make things even easier, R also has a <code>summary()</code> function that calculates a number of these routine statistics simultaneously. After running the <code>summary()</code> function on our assault incident variable, you should see you get the minimum (Min.) and maximum (Max.) values of the <em>assault_09_11</em> column; its first (1st Qu.) and third (3rd Qu.) quartiles that comprise the interquartile range; its the mean and the median. The built-in R <code>summary()</code> function does not calculate the standard deviation. There are functions in other libraries that calculate more detailed descriptive statistics,</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="examining-data-i.html#cb131-1" aria-hidden="true"></a><span class="co"># calculate the most common descriptive statistics for the assault incident variable</span></span>
<span id="cb131-2"><a href="examining-data-i.html#cb131-2" aria-hidden="true"></a><span class="kw">summary</span>(London.Ambulance<span class="op">$</span>Assault_<span class="dv">09</span>_<span class="dv">11</span>)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0    86.0   146.0   173.5   233.0  1582.0</code></pre>
</div>
<div id="recap-1" class="section level4 unnumbered">
<h4>Recap</h4>
<p>In this section you have learnt how to:</p>
<ol style="list-style-type: decimal">
<li>Calculate the range, interquartile range, and standard deviation in R.</li>
<li>Create a simple boxplot using the <code>boxplot()</code> function.</li>
<li>Quickly get common descriptive statistics using the <code>summary()</code> function.</li>
</ol>
</div>
</div>
<div id="seminar-w02" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Seminar</h2>
<p>Please find the seminar task and seminar questions for this week’s seminar below.</p>
<div class="note">
<p><strong>Note</strong><br/>
Please make sure that you have executed the seminar task and have answered the seminar questions before the seminar!</p>
</div>
<div id="seminar-task" class="section level4 unnumbered">
<h4>Seminar task</h4>
<p>Using the <code>London.Ambulance</code> object:</p>
<ol style="list-style-type: decimal">
<li>Create a new object / data set that <strong>only</strong> contains data for ward type <em>Multicultural Metropolitan</em>.</li>
<li>Create a new object / data set that <strong>only</strong> contains data for ward type <em>Prospering Metropolitan</em>.</li>
</ol>
<div class="note">
<p><strong>Note</strong><br/>
Creating a new object from an existing object is called creating a <strong>subset</strong> of your data. There are many ways of creating a subset, but one way of doing it is by using the following syntax: <code>London.Assault[London.Assault$WardType == 'Multicultural Metropolitan',]</code>.</p>
</div>
<p>For <strong>both</strong> new objects:</p>
<ol style="list-style-type: decimal">
<li>Calculate the median, mean, range, interquartile range, and standard deviation for the <em>Assault_09_11</em> variable.</li>
<li>Create a boxplot of the <em>Assault_09_11</em> variable.</li>
</ol>
</div>
<div id="seminar-questions" class="section level4 unnumbered">
<h4>Seminar questions</h4>
<ol style="list-style-type: decimal">
<li>Explain why each of these statistics are useful and what type of data are required to calculate them:</li>
</ol>
<ul>
<li>Mode</li>
<li>Median</li>
<li>Mean</li>
<li>Range</li>
<li>Interquartile Range</li>
<li>Standard Deviation</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Compare the results of the descriptive statistics you have calculated for your <em>Multicultural Metropolitan</em> object / data set with the results of the descriptive statistics you have calculated for you <em>Prospering Metropolitan</em> object / data set. What do these differences tell us? In which of these two ward types are the data more clustered? In which of these two ward types are the data more dispersed?</li>
</ol>
</div>
<div id="seminar-link" class="section level4 unnumbered">
<h4>Seminar link</h4>
<p>Seminars for all groups take place on <strong>Thursday morning</strong>. You can find the <strong>Zoom</strong> link to your seminar group on <a href="https://moodle.ucl.ac.uk/course/view.php?id=6845">Moodle</a>.</p>
</div>
</div>
<div id="byl-w02" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Before you leave</h2>
<p>Save your R script by pressing the <strong>Save</strong> button in the script window. <a href="https://www.youtube.com/watch?v=Wmc8bQoL-J0">That is it for this week</a>!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="understanding-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="examining-data-ii.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jtvandijk/POLS0008_20202021/edit/master/02-week02.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["https://github.com/jtvandijk/POLS0008_20202021/raw/master/02-week02.Rmd"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
